<?php

namespace AppBundle\Repository;

/**
 * UserLibraryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLibraryRepository extends \Doctrine\ORM\EntityRepository
{
}
